# Generated by Django 3.1.7 on 2021-02-28 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default='', max_length=200)),
                ('middle_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('salary', models.PositiveIntegerField(default=0)),
                ('salary_due_date', models.DateField()),
                ('releasing_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
