# Generated by Django 3.1.7 on 2021-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210228_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.CharField(default='43701', max_length=5, verbose_name='zip code'),
        ),
    ]
