# Generated by Django 3.1.7 on 2021-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210228_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.CharField(default='00000', max_length=7, verbose_name='pin code'),
        ),
    ]
