# Generated by Django 3.1.7 on 2021-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210228_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
