# Generated by Django 3.1.7 on 2021-02-28 14:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210228_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=phone_field.models.PhoneField(default='12231', max_length=31),
            preserve_default=False,
        ),
    ]
