# Generated by Django 3.1.7 on 2021-03-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_booking', '0001_initial'),
        ('managecinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='book_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinemadeck'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat_manager'),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat'),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='available_slots',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinemaarrangeslot'),
        ),
    ]
