# Generated by Django 3.1.7 on 2021-02-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecinema', '0004_delete_cinemaslot'),
        ('cinema_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_slots',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinemaarrangeslot'),
        ),
    ]
