# Generated by Django 3.1.7 on 2021-02-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cinema', '0007_auto_20210226_2203'),
        ('cinema_booking', '0002_available_slots_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_slots',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_cinema.cinemaarrangeslot'),
        ),
    ]
