# Generated by Django 3.1.7 on 2021-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0004_auto_20210228_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_slots',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookseat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seat_manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
