# Generated by Django 3.1.7 on 2021-02-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecinema', '0010_auto_20210227_1022'),
        ('cinema_booking', '0004_available_slots_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_slots',
            name='deck',
        ),
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinema_deck')),
            ],
        ),
    ]
