# Generated by Django 3.1.7 on 2021-02-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cinema', '0010_auto_20210227_1022'),
        ('cinema_booking', '0005_auto_20210227_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seats',
            new_name='Seat',
        ),
    ]
