# Generated by Django 3.1.7 on 2021-02-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0005_auto_20210228_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat_manager',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
