# Generated by Django 3.1.7 on 2021-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0006_auto_20210227_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_slots',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='available_slots',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='available_slots',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
