# Generated by Django 3.1.7 on 2021-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0007_auto_20210227_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
