# Generated by Django 3.1.7 on 2021-03-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0008_auto_20210228_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat', unique=True),
        ),
    ]
