# Generated by Django 3.1.7 on 2021-03-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0009_auto_20210301_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat'),
        ),
    ]
