# Generated by Django 3.1.7 on 2021-02-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0010_seat_date_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat_manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='date_slots',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat_manager'),
            preserve_default=False,
        ),
    ]
