# Generated by Django 3.1.7 on 2021-02-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0012_seat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='available_slot',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.available_slots'),
            preserve_default=False,
        ),
    ]
