# Generated by Django 3.1.7 on 2021-02-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0015_bookseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
