# Generated by Django 3.1.7 on 2021-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210228_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(default='2021-02-28'),
            preserve_default=False,
        ),
    ]
