# Generated by Django 3.1.7 on 2021-03-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_unread_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_notification',
        ),
    ]
