# Generated by Django 3.1.7 on 2021-03-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Booked', 'Booked'), ('Cancel_Book', 'Cancel_Book')], default='Booked', max_length=50)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.bookseat')),
            ],
        ),
    ]
