# Generated by Django 3.1.7 on 2021-03-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0011_auto_20210301_1257'),
        ('cinema_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seat',
            field=models.OneToOneField(default=49, on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.bookseat'),
            preserve_default=False,
        ),
    ]
