# Generated by Django 3.1.7 on 2021-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_notification', '0002_notification_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
