# Generated by Django 3.1.7 on 2021-02-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cinema', '0002_auto_20210226_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinemaSlots',
            new_name='CinemaSlot',
        ),
    ]
