# Generated by Django 3.1.7 on 2021-02-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cinema', '0005_auto_20210226_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaarrangeslot',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_cinema.cinema'),
        ),
    ]
