# Generated by Django 3.1.7 on 2021-02-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cinema', '0010_auto_20210227_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinemaSlotsDuration',
            new_name='MovieDurationSlot',
        ),
    ]
