# Generated by Django 3.1.7 on 2021-03-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_feedback', '0001_initial'),
        ('managecinema', '0003_cinemaarrangeslot_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaarrangeslot',
            name='review',
        ),
        migrations.AddField(
            model_name='cinemadeck',
            name='review',
            field=models.ManyToManyField(to='cinema_feedback.Review'),
        ),
    ]
