# Generated by Django 3.1.7 on 2021-02-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecinema', '0003_auto_20210226_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinemaSlot',
        ),
    ]
