# Generated by Django 3.1.7 on 2021-03-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecinema', '0004_auto_20210302_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemadeck',
            name='review',
        ),
    ]
