# Generated by Django 3.1.7 on 2021-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_feedback', '0001_initial'),
        ('managecinema', '0005_remove_cinemadeck_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='all_review',
            field=models.ManyToManyField(to='cinema_feedback.Review'),
        ),
    ]
