# Generated by Django 3.1.7 on 2021-02-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecinema', '0008_auto_20210227_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
