# Generated by Django 3.1.7 on 2021-02-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking', '0013_seat_available_slot'),
        ('managecinema', '0011_auto_20210227_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cinema_Deck',
            new_name='CinemaDeck',
        ),
    ]
