# Generated by Django 3.1.7 on 2021-02-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210225_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
    ]
